### ISSUE TITLE
Variant details table TODOs

### ISSUE THREAD

**Issue by marc-sturm** [imgag/GSvarWeb#43]
Variant details table:
- [x] Add link to gnomAD
- [x] Add link for domain
- [x] Color pathogenicity predictions
- [x] Color HGMD/ClinVar entry
- [x] Add tooltip with full text to HGMD/ClinVar/OMIM
- [x] Add 'Google' link as in GSvar

Main variant table:
- [x] Check if colors are properly implemented
- [x] tooltip for all columns

General:
- [x] Add logout button

**Comment by Fohlen** [comment]
The coloring can be found at https://github.com/imgag/ngs-bits/blob/3fd0d2e3e38a07c6e5fe246ba4e0f93e8ff3b45c/src/GSvar/VariantTable.cpp#L114

**Comment by Fohlen** [comment]
All colors that can be implemented have been implemented (`NGSD`, `validation` and `comment` are virtual fields calculated using `NGSD`)
